<div style="margin-top: 1rem">
    <?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $order = $objectManager
            ->create(\Magento\Sales\Model\Order::class)
            ->load($block->getRequest()
            ->getParam('order_id'));
    $paymentData = $order->getPayment()->getData()['additional_information'];
    ?>
    <table class="order-payment-additional-info">
        <tbody>
            <tr>
                <td>Payment Method</td>
                <td>
                    <?= /* @noEscape */ isset($paymentData['payment_method'])
                    ? $paymentData['payment_method']
                    : 'N/A' ?>
                </td>
            </tr>
            <!-- TODO: display wallet if applicable -->
        </tbody>
    </table>
</div>
