<?php

/** @var $block \Yedpay\YedpayMagento\Block\Success */ ?>
<div class="checkout-success">
<?php $request_status = filter_input(INPUT_GET, 'status') ?>
    <?php if ($request_status === 'cancelled'): ?>
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $custom_id = filter_input(INPUT_GET, 'custom_id');
        $order = $objectManager->create(\Magento\Sales\Model\Order::class)->loadByIncrementId($custom_id);
        $order->setState('canceled')->setStatus('canceled');
        $order->save();
        ?>
        <h1><?= $block->escapeHtmlAttr('Payment failure') ?></h1>
        <p><?= $block->escapeHtmlAttr('The order is cancelled by the customer.') ?></p>
    <?php elseif ($block->getOrderId()): ?>
        <h1><?= $block->escapeHtmlAttr('Thank you for your purchase!') ?></h1>
        <?php if ($block->getCanViewOrder()): ?>

        <?php else: ?>
            <?php $orderId = $block->escapeHtml($block->getOrderId()) ?>
            <p><?=/* @noEscape */ 'Your order # is: ' . $orderId ?></p>
        <?php endif; ?>

        <?php $itemNo = (int) $block->getOrder()->getTotalQtyOrdered() ?>
        <p><?= /* @noEscape */ 'You ordered ' . $itemNo . 'items' ?></p>
        <p><?= $block->escapeHtmlAttr('Payment method: ' . $block->getPaymentMethod()) ?></p>
    <?php endif; ?>

    <br />
    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= /* @noEscape */ $block->getUrl() ?>">
               <span><?= /* @escapeNotVerified */ ('Continue Shopping') ?></span>
            </a>
        </div>
    </div>
</div>
